version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    groups:
      actions-minor:
        update-types: ["minor", "patch"]
      actions-major:
        update-types: ["major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    groups:
      npm-minor:
        update-types: ["minor", "patch"]
      npm-major:
        update-types: ["major"]
